# Generated by Django 3.2.3 on 2021-05-21 07:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DBConnInfo',
            fields=[
                ('db_id', models.AutoField(primary_key=True, serialize=False, verbose_name='#')),
                ('db_type', models.IntegerField(choices=[(1, 'Oracle'), (2, 'Mysql'), (3, 'Redis')], default=1, verbose_name='数据库类型')),
                ('db_nickname', models.CharField(max_length=128, verbose_name='数据库别名')),
                ('db_host', models.GenericIPAddressField(verbose_name='数据库主机')),
                ('db_port', models.IntegerField(validators=[django.core.validators.MaxValueValidator(65535), django.core.validators.MinValueValidator(0)], verbose_name='端口号')),
                ('db_username', models.CharField(blank=True, max_length=64, verbose_name='数据库用户名')),
                ('db_password', models.CharField(max_length=64, verbose_name='数据库密码')),
                ('db_name', models.CharField(blank=True, max_length=64, verbose_name='数据库名称')),
                ('db_last_modify', models.DateTimeField(auto_now=True, verbose_name='上一次修改时间')),
            ],
            options={
                'verbose_name': '数据库连接信息',
                'verbose_name_plural': '数据库连接信息',
                'ordering': ['db_id'],
            },
        ),
    ]
