# Generated by Django 3.2.3 on 2021-05-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dbconninfo',
            table='DB_CONN_INFO',
        ),
    ]
