# Generated by Django 3.2.3 on 2021-05-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanager', '0002_alter_dbconninfo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbconninfo',
            name='db_host',
            field=models.CharField(max_length=128, verbose_name='数据库主机'),
        ),
    ]
