"""
Django settings for Sniper project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xxxxx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

APPEND_SLASH = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'dbmanager',
    'apimanager',
    'schedule',
    'simpleui',
    'jsoneditor',
    'django_db_reconnect',
    'django_celery_beat',
    'django_celery_results',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Sniper.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Sniper.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'sniper',
        'USER': 'root',
        'PASSWORD': 'xxx',
        'HOST': 'localhost',
        'PORT': 3306,
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'
# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "common_static")
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# SIMPLE-UI 配置
# SIMPLEUI_HOME_TITLE = '百度一下你就知道'
# 脱机模式
SIMPLEUI_STATIC_OFFLINE = True
# 不上传统计分析信息
SIMPLEUI_ANALYSIS = False
# 首页-最近动作
SIMPLEUI_HOME_ACTION = True
# 首页-服务器信息
SIMPLEUI_HOME_INFO = False

SIMPLEUI_CONFIG = {
    'system_keep': False,
    # 菜单名
    'menu_display': ['数据库管理', '接口管理', '计划任务管理', '认证和授权'],
    'dynamic': False,  # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时动态展示菜单内容
    'menus': [
        {
            'name': '数据库管理',
            'icon': 'fas fa-database',
            'models': [
                {
                    'name': '数据库连接信息',
                    'icon': 'fa fa-database',
                    'url': '/admin/dbmanager/dbconninfo/'
                },
            ]
        },
        {
            'name': '接口管理',
            'icon': 'fas fa-cog',
            'models': [
                {
                    'name': '接口信息',
                    'icon': 'fa fa-plug',
                    'url': '/admin/apimanager/apiinfo/'
                },
            ]
        },
        {
            'name': '计划任务管理',
            'icon': 'fas fa-calendar-alt',
            'models': [
                {
                    'name': '计划任务信息',
                    'icon': 'fa fa-calendar',
                    'url': '/admin/schedule/scheduleextinfo/'
                },
                {
                    'name': '定时管理',
                    'icon': 'fa fa-hourglass-half',
                    'models': [{
                        'name': 'Crontab',
                        'icon': 'fa fa-asterisk',
                        'url': '/admin/django_celery_beat/crontabschedule/'
                    }, {
                        'name': '时间间隔',
                        'icon': 'fa fa-clock',
                        'url': '/admin/django_celery_beat/intervalschedule/'
                    }, {
                        'name': '指定时间',
                        'icon': 'fa fa-calendar-check',
                        'url': '/admin/django_celery_beat/clockedschedule/'
                    }
                        # {
                        #    'name': '日出日落',
                        #    'icon': 'fa fa-sun',
                        #    'url': '/admin/django_celery_beat/solarschedule/'
                        # },
                    ]
                },

                {
                    'name': '计划任务结果',
                    'icon': 'fa fa-tasks',
                    'url': '/admin/django_celery_results/taskresult/'
                },
            ]
        },
        {
            'name': '认证和授权',
            'icon': 'fas fa-shield-alt',
            'models': [
                {
                    'name': '用户',
                    'icon': 'far fa-user',
                    'url': '/admin/auth/user/'
                },
                {
                    'name': '用户组',
                    'icon': 'fas fa-users-cog',
                    'url': '/admin/auth/group/'
                },
            ]
        },
    ]
}

# JSONEDITOR 参数
JSON_EDITOR_JS = '/static/jsoneditor/jsoneditor.js'
JSON_EDITOR_CSS = '/static/jsoneditor/jsoneditor.css'

# Celery定时参数
CELERY_ENABLE_UTC = False
CELERY_TIMEZONE = TIME_ZONE
DJANGO_CELERY_BEAT_TZ_AWARE = False
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERYD_FORCE_EXECV = True  # 非常重要,有些情况下可以防止死锁
CELERY_BROKER_URL = 'redis://:xxx@127.0.0.1:6379/0'  # Broker配置，使用Redis作为消息中间件
CELERY_RESULT_BACKEND = 'django-db'  # BACKEND配置，这里存到数据库
CELERY_RESULT_SERIALIZER = 'json'  # 结果序列化方案
CELERYD_MAX_TASKS_PER_CHILD = 20  # 每个worker最多执行万100个任务就会被销毁
# celery 的启动工作数量设置
CELERY_WORKER_CONCURRENCY = 10
