# Generated by Django 3.2.3 on 2021-05-25 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apimanager', '0008_auto_20210525_1043'),
        ('django_celery_beat', '0016_auto_20210521_1547'),
        ('dbmanager', '0002_alter_dbconninfo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleExtInfo',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False, verbose_name='#')),
                ('task_type', models.IntegerField(choices=[(1, '执行SQL'), (2, '接口检查')], default=1, verbose_name='任务类型')),
                ('exec_sql', models.TextField(blank=True, null=True, verbose_name='SQL语句')),
                ('sql_alert', models.CharField(blank=True, max_length=1024, null=True, verbose_name='SQL告警条件')),
                ('api_method', models.IntegerField(blank=True, choices=[(1, 'POST'), (2, 'GET')], null=True, verbose_name='请求方式')),
                ('api_header', models.JSONField(blank=True, null=True, verbose_name='请求头')),
                ('api_params', models.JSONField(blank=True, null=True, verbose_name='请求参数')),
                ('api_alert', models.CharField(blank=True, max_length=1024, null=True, verbose_name='API告警条件')),
                ('retry_time', models.IntegerField(default=3, verbose_name='重试次数')),
                ('check_api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='apimanager.apiinfo', verbose_name='检测接口')),
                ('run_db', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dbmanager.dbconninfo', verbose_name='SQL运行数据库')),
                ('schedule_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
        ),
    ]
