# Generated by Django 3.2.3 on 2021-05-27 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0016_auto_20210521_1547'),
        ('schedule', '0002_auto_20210525_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleextinfo',
            name='schedule_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask', verbose_name='计划任务'),
        ),
    ]
