# Generated by Django 3.2.3 on 2021-05-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_scheduleextinfo_schedule_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleextinfo',
            name='task_type',
        ),
        migrations.AlterField(
            model_name='scheduleextinfo',
            name='retry_time',
            field=models.IntegerField(default=1, verbose_name='重试次数'),
        ),
    ]
