# Generated by Django 3.2.3 on 2021-06-02 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apimanager', '0008_auto_20210525_1043'),
        ('dbmanager', '0003_alter_dbconninfo_db_host'),
        ('schedule', '0004_auto_20210531_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleextinfo',
            name='check_api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apimanager.apiinfo', verbose_name='检测接口'),
        ),
        migrations.AlterField(
            model_name='scheduleextinfo',
            name='run_db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbmanager.dbconninfo', verbose_name='SQL运行数据库'),
        ),
    ]
