# Generated by Django 3.2.3 on 2021-06-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20210602_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleextinfo',
            name='retry_time',
        ),
        migrations.AlterField(
            model_name='scheduleextinfo',
            name='api_method',
            field=models.TextField(blank=True, choices=[('POST', 'POST'), ('GET', 'GET')], max_length=10, null=True, verbose_name='请求方式'),
        ),
    ]
