# Generated by Django 3.2.3 on 2021-05-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIInfo',
            fields=[
                ('api_id', models.AutoField(primary_key=True, serialize=False, verbose_name='#')),
                ('api_type', models.IntegerField(choices=[(1, 'HTTP/HTTPS'), (2, 'WebSocket')], default=1, verbose_name='接口类型')),
                ('api_nickname', models.CharField(max_length=128, verbose_name='接口名称')),
                ('api_addr', models.CharField(max_length=256, verbose_name='接口地址')),
                ('api_method', models.IntegerField(choices=[(1, 'POST'), (2, 'GET')], default=1, verbose_name='请求方式')),
                ('api_username', models.CharField(blank=True, max_length=64, verbose_name='接口登录用户名')),
                ('api_password', models.CharField(max_length=64, verbose_name='接口登录密码')),
                ('api_params', models.CharField(max_length=1024, verbose_name='请求参数')),
                ('api_last_modify', models.DateTimeField(auto_now=True, verbose_name='上一次修改时间')),
            ],
            options={
                'verbose_name': '接口信息',
                'verbose_name_plural': '接口信息',
                'ordering': ['api_id'],
            },
        ),
    ]
