# Generated by Django 3.2.3 on 2021-05-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimanager', '0002_alter_apiinfo_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='api_password',
            field=models.CharField(blank=True, max_length=64, verbose_name='接口登录密码'),
        ),
    ]
