# Generated by Django 3.2.3 on 2021-05-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimanager', '0003_alter_apiinfo_api_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='api_params',
            field=models.CharField(blank=True, max_length=1024, verbose_name='请求参数'),
        ),
    ]
