# Generated by Django 3.2.3 on 2021-05-21 08:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apimanager', '0005_alter_apiinfo_api_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiinfo',
            name='api_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, verbose_name='请求参数'),
        ),
    ]
