# Generated by Django 3.2.3 on 2021-05-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apimanager', '0007_alter_apiinfo_api_params'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiinfo',
            name='api_method',
        ),
        migrations.RemoveField(
            model_name='apiinfo',
            name='api_params',
        ),
    ]
